version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    environment:
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://storage:10001/devstoreaccount1; 
    depends_on:
      - storage
  worker:
    image: ${DOCKER_REGISTRY-}worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - StorageConnectionString=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=http://storage:10001/devstoreaccount1;
      - HubProcessUrl=http://web/process
    depends_on:
      - storage
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --queuePort 10001 --queueHost 0.0.0.0
